# Week 6 Live Code
library(tidyverse)

surveys <- read_csv("data/portal_data_joined.csv")

# remove NAs from weight, hindfoot_length, and sex.

surveys_complete <- surveys %>% 
  filter(!is.na(weight), !is.na(hindfoot_length), !is.na(sex))

#  remove rare species (<50). note: n is generated by tally function.

species_counts <- surveys_complete %>% 
  group_by(species_id) %>% 
  tally() %>% 
  filter(n >= 50)

surveys_complete <- surveys_complete %>% 
  filter(species_id %in% species_counts$species_id)

# Writing your dataframe to .csv

write_csv(surveys_complete, path = "data_output/surveys_complete.csv")

#### ggplot time! ===================================
# Tue Feb 12 14:31:21 2019 ------------------------------


# ggplot(data = DATA, mapping = aes(MAPPINGS)) + geom_function()

ggplot(data = surveys_complete)

# define a mapping

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))

# add a layer

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point()

# saving a plot object
surveys_plot <- ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))

surveys_plot +
  geom_point()

# Challenge
install.packages("hexbin")

surveys_plot +
  geom_hex()

# we're going to build plots from the ground

# modifying whole geom appearances

surveys_complete %>% 
  ggplot(aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, color = "tomato") # alpha changed the transparency of points in plot

# using data in a geom

surveys_complete %>% 
  ggplot(aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, aes(color = species_id)) #make sure to wrap in aes

# putting color as a global aesthetic

surveys_complete %>% 
  ggplot(aes(x = weight, y = hindfoot_length, color = species_id)) +
  geom_point(alpha = 0.1)

# using a little jitter
# jitter does pretty much the same thing as geom_point but just shifts the points a little bit
# this is usefull when you have a lot of overlap in your data
# hard to see in this example because we have so much data but could be more useful with smaller data set

surveys_complete %>% 
  ggplot(aes(x = weight, y = hindfoot_length, color = species_id)) +
  geom_jitter(alpha = 0.1) 

# moving on to boxplots

surveys_complete %>% 
  ggplot(aes(x = species_id, y = weight)) +
  geom_boxplot()

# adding point to boxplot
# placing jitter before boxplot places boxplot on top (easier to see)

surveys_complete %>% 
  ggplot(aes(x = species_id, y = weight)) +
  geom_jitter(alpha = 0.1, color = "tomato") +
  geom_boxplot(alpha = 0) 

# plotting time series

yearly_counts <- surveys_complete %>% 
  count(year, species_id)

yearly_counts %>% 
  ggplot(aes(x = year, y = n, group = species_id, color = species_id)) +
  geom_line()

# facetting
yearly_counts %>% 
  ggplot(aes(x =  year, y = n, color = species_id)) +
  geom_line() +
  facet_wrap(~ species_id)

# including sex
Yearly_sex_counts <- surveys_complete %>% 
  count(year, species_id, sex)

ysx_plot <- Yearly_sex_counts %>% 
  ggplot(aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(~ species_id) +
  theme_bw() + # changing theme
  theme(panel.grid = element_blank()) # getting rid of background

# a little more facetting

yearly_sex_weight <- surveys_complete %>% 
  group_by(year, sex, species_id) %>% 
  summarise(avg_weight = mean(weight))

yearly_sex_weight %>% 
  ggplot(aes(x = year, y = avg_weight, color = species_id)) +
  geom_line() +
  facet_grid(sex ~ .) # facet_grid uses rows ~ columns for faceting. the "."

# adding labels and stuff

ysx_plot <- Yearly_sex_counts %>% 
  ggplot(aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(~ species_id) +
  theme_bw() + # changing theme
  theme(panel.grid = element_blank()) +
  labs(title = "Observed species through time", x = "Year of oberservation", y = "Number of species") +
  theme(text = element_text(size = 16)) +
  theme(axis.text = element_text(color = "grey20", size = 12, angle = 90, hjust = 0.5, vjust = 0.5))

ysx_plot

# ggsave
ysx_plot

ggsave("figures/my_test_facet_plot.jpeg", height = 8, width = 8)


  
